In [1]:
import torch

a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]], dtype=torch.int32)

print(a)
print("Kích thước:", a.shape)
print("Số chiều:", a.ndim)
print("Kiểu dữ liệu:", a.dtype)

c:\Users\vugia\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\torch\_subclasses\functional_tensor.py:368: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
Kích thước: torch.Size([2, 3])
Số chiều: 2
Kiểu dữ liệu: torch.int32


In [2]:
import torch

torch.manual_seed(42)

a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)

f = torch.full((5, 5), 10)

print("Tensor rand:")
print(a)

print("\nTensor randn:")
print(b)

print("\nTensor zeros:")
print(c)

print("\nTensor ones:")
print(d)

print("\nMa trận đơn vị:")
print(e)

print("\nTensor 5 x 5 toàn số 10:")
print(f)

Tensor rand:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor randn:
tensor([[ 2.2082, -0.6380,  0.4617,  0.2674],
        [ 0.5349,  0.8094,  1.1103, -1.6898],
        [-0.9890,  0.9580,  1.3221,  0.8172]])

Tensor zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Tensor ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Ma trận đơn vị:
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

Tensor 5 x 5 toàn số 10:
tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


In [3]:
import torch

a = torch.zeros(2, 3, 4)

print("Tensor:")
print(a)

print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


In [4]:
import torch

torch.manual_seed(42)

a = torch.randn(3, 4, 5)

print("Original tensor:")
print(a)

print("\nTensor a[1]:")
print(a[1])

print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

print("\nHai phần tử cuối cùng trên chiều thứ ba:")
print(a[:, :, -2:])

Original tensor:
tensor([[[ 1.9269,  1.4873,  0.9007, -2.1055,  0.6784],
         [-1.2345, -0.0431, -1.6047, -0.7521,  1.6487],
         [-0.3925, -1.4036, -0.7279, -0.5594, -0.7688],
         [ 0.7624,  1.6423, -0.1596, -0.4974,  0.4396]],

        [[-0.7581,  1.0783,  0.8008,  1.6806,  1.2791],
         [ 1.2964,  0.6105,  1.3347, -0.2316,  0.0418],
         [-0.2516,  0.8599, -1.3847, -0.8712, -0.2234],
         [ 1.7174,  0.3189, -0.4245,  0.3057, -0.7746]],

        [[-1.5576,  0.9956, -0.8798, -0.6011,  0.3672],
         [ 0.1754,  1.3852, -0.4459,  1.4451,  0.8564],
         [ 2.2181,  0.5232,  1.1754,  0.5612, -0.4527],
         [-0.7718, -0.1722,  0.5238,  0.0566,  0.4263]]])

Tensor a[1]:
tensor([[-0.7581,  1.0783,  0.8008,  1.6806,  1.2791],
        [ 1.2964,  0.6105,  1.3347, -0.2316,  0.0418],
        [-0.2516,  0.8599, -1.3847, -0.8712, -0.2234],
        [ 1.7174,  0.3189, -0.4245,  0.3057, -0.7746]])

Tensor a[1:, 2:4]:
tensor([[[-0.2516,  0.8599, -1.3847, -0.8712, -0.2

In [5]:
import torch

torch.manual_seed(42)

a = torch.randn(3, 4)

print("Original:")
print(a)

print("\nFlatten:")
print(a.ravel())

print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

print("\nReshape to 2 x 6:")
print(a.reshape(2, 6))

print("\nSố phần tử ban đầu:", a.numel())
print("Số phần tử sau reshape 3 x 2 x 2:",
      a.reshape(3, 2, 2).numel())
print("Số phần tử sau reshape 2 x 6:",
      a.reshape(2, 6).numel())

Original:
tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380],
        [ 0.4617,  0.2674,  0.5349,  0.8094]])

Flatten:
tensor([ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229, -0.1863,  2.2082, -0.6380,
         0.4617,  0.2674,  0.5349,  0.8094])

Reshape to 3 x 2 x 2:
tensor([[[ 0.3367,  0.1288],
         [ 0.2345,  0.2303]],

        [[-1.1229, -0.1863],
         [ 2.2082, -0.6380]],

        [[ 0.4617,  0.2674],
         [ 0.5349,  0.8094]]])

Reshape to 2 x 6:
tensor([[ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617,  0.2674,  0.5349,  0.8094]])

Số phần tử ban đầu: 12
Số phần tử sau reshape 3 x 2 x 2: 12
Số phần tử sau reshape 2 x 6: 12


In [6]:
import torch

torch.manual_seed(42)

a = torch.randn(2, 3)
b = torch.randn(2, 3)

print("a:")
print(a)

print("b:")
print(b)

print("\na + b:")
print(a + b)

print("\na / b:")
print(a / b)

print("\na^2:")
print(a ** 2)

print("\nMatrix multiplication:")
print(a @ b.T)

a:
tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863]])
b:
tensor([[ 2.2082, -0.6380,  0.4617],
        [ 0.2674,  0.5349,  0.8094]])

a + b:
tensor([[ 2.5449, -0.5092,  0.6961],
        [ 0.4977, -0.5880,  0.6230]])

a / b:
tensor([[ 0.1525, -0.2019,  0.5079],
        [ 0.8615, -2.0992, -0.2302]])

a^2:
tensor([[0.1134, 0.0166, 0.0550],
        [0.0531, 1.2608, 0.0347]])

Matrix multiplication:
tensor([[ 0.7695,  0.3487],
        [ 1.1390, -0.6898]])


In [7]:
import torch

torch.manual_seed(42)

a = torch.randn(3, 4)

print(a)

print("\nMean:")
print(torch.mean(a, dim=0))

print("\nStandard deviation:")
print(torch.std(a, dim=0))

print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))

print("\nMean với dim=1:")
print(torch.mean(a, dim=1))

print("\nStandard deviation với dim=1:")
print(torch.std(a, dim=1))

print("\nCumulative sum với dim=1:")
print(torch.cumsum(a, dim=1))

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380],
        [ 0.4617,  0.2674,  0.5349,  0.8094]])

Mean:
tensor([-0.1082,  0.0699,  0.9925,  0.1339])

Standard deviation:
tensor([0.8810, 0.2325, 1.0635, 0.7285])

Cumulative sum:
tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-0.7862, -0.0575,  2.4427, -0.4077],
        [-0.3245,  0.2098,  2.9776,  0.4017]])

Mean với dim=1:
tensor([0.2326, 0.0653, 0.5183])

Standard deviation với dim=1:
tensor([0.0849, 1.4789, 0.2245])

Cumulative sum với dim=1:
tensor([[ 0.3367,  0.4655,  0.7000,  0.9303],
        [-1.1229, -1.3092,  0.8990,  0.2610],
        [ 0.4617,  0.7290,  1.2639,  2.0733]])


In [8]:
import torch

x = torch.tensor(3.6, requires_grad=True)

y = x * x

y.backward()

print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


In [12]:
import numpy as np
import torch

np.random.seed(42)
torch.manual_seed(42)

polynomial = np.poly1d([1, 2, 3])

N = 20

X = np.random.randn(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

w = torch.randn(3, 1, requires_grad=True)

x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)

for epoch in range(1000):

    optimizer.zero_grad()

    y_pred = x @ w

    mse = torch.mean(torch.square(y - y_pred))

    mse.backward()

    optimizer.step()

print("Learned coefficients:")
print(w)

Learned coefficients:
tensor([[1.0087],
        [2.0033],
        [2.5330]], requires_grad=True)


In [13]:
import random
import torch

random.seed(42)

A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)

EPOCHS = 2000

optimizer = torch.optim.NAdam(
    [A, B, C, D],
    lr=0.01
)

for _ in range(EPOCHS):

    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2

    sqerr = (
        y1*y1 +
        y2*y2 +
        y3*y3 +
        y4*y4
    )

    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()

print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)

A = tensor(4.7772, requires_grad=True)
B = tensor(4.2227, requires_grad=True)
C = tensor(3.2228, requires_grad=True)
D = tensor(2.2227, requires_grad=True)


In [14]:
import torch

X = torch.arange(24)

print("Tensor X:")
print(X)

print("\nX reshape 4 x 6:")
print(X.reshape(4, 6))

print("\nX reshape 2 x 12:")
print(X.reshape(2, 12))

print("\nX reshape 2 x 3 x 4:")
print(X.reshape(2, 3, 4))

Tensor X:
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])

X reshape 4 x 6:
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])

X reshape 2 x 12:
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

X reshape 2 x 3 x 4:
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


In [15]:
import torch

torch.manual_seed(42)

A = torch.randn(3, 4)
B = torch.randn(3, 4)

print("A:")
print(A)

print("\nB:")
print(B)

print("\nA + B:")
print(A + B)

print("\nA * B:")
print(A * B)

print("\nA / B:")
print(A / B)

print("\nTrung bình theo cột:")
print(torch.mean(A, dim=0))

print("\nĐộ lệch chuẩn theo cột:")
print(torch.std(A, dim=0))

A:
tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380],
        [ 0.4617,  0.2674,  0.5349,  0.8094]])

B:
tensor([[ 1.1103, -1.6898, -0.9890,  0.9580],
        [ 1.3221,  0.8172, -0.7658, -0.7506],
        [ 1.3525,  0.6863, -0.3278,  0.7950]])

A + B:
tensor([[ 1.4470, -1.5610, -0.7545,  1.1883],
        [ 0.1993,  0.6309,  1.4424, -1.3886],
        [ 1.8142,  0.9537,  0.2071,  1.6043]])

A * B:
tensor([[ 0.3738, -0.2177, -0.2319,  0.2207],
        [-1.4846, -0.1523, -1.6911,  0.4789],
        [ 0.6244,  0.1835, -0.1753,  0.6434]])

A / B:
tensor([[ 0.3032, -0.0762, -0.2371,  0.2404],
        [-0.8493, -0.2280, -2.8834,  0.8500],
        [ 0.3413,  0.3895, -1.6320,  1.0181]])

Trung bình theo cột:
tensor([-0.1082,  0.0699,  0.9925,  0.1339])

Độ lệch chuẩn theo cột:
tensor([0.8810, 0.2325, 1.0635, 0.7285])


In [17]:
import torch

x = torch.tensor(2.0, requires_grad=True)

y = 2*x**2 + 5*x + 3

y.backward()

print("y =", y)
print("dy/dx =", x.grad)


y = tensor(21., grad_fn=<AddBackward0>)
dy/dx = tensor(13.)


In [18]:
import numpy as np
import torch

np.random.seed(42)
torch.manual_seed(42)

polynomial = np.poly1d([2, -3, 5])

N = 20

X = np.random.randn(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

w = torch.randn(3, 1, requires_grad=True)

x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)

for epoch in range(1000):

    optimizer.zero_grad()

    y_pred = x @ w

    mse = torch.mean(torch.square(y - y_pred))

    mse.backward()

    optimizer.step()

print("Learned coefficients:")
print(w)

Learned coefficients:
tensor([[ 2.0462],
        [-2.8942],
        [ 2.7752]], requires_grad=True)
